server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://172.17.0.1:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets: ['localhost']
        labels:
          job: varlogs
          __path__: /var/log/*log

  - job_name: docker
    static_configs:
      - targets: ['localhost']
        labels:
          job: docker
          app: outsourcing_backend
          __path__: /var/lib/docker/containers/*/*-json.log
    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            attrs: attrs
            container_name: attrs.container_name
            image: attrs.image
      - labels:
          stream:
          container_name:
          image:
      - output:
          source: output

  - job_name: app_logs
    static_configs:
      - targets: ['localhost']
        labels:
          job: app_logs
          app: outsourcing_backend
          __path__: /var/log/app/*log
    pipeline_stages:
      - json:
          expressions:
            level: level
            message: message
            timestamp: timestamp
      - labels:
          level:
      - timestamp:
          source: timestamp
          format: RFC3339

  - job_name: node_app_logs
    static_configs:
      - targets: ['localhost']
        labels:
          job: node_app
          app: outsourcing_backend
          __path__: /var/lib/docker/containers/*node-app*/*-json.log
    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            attrs: attrs
            container_name: attrs.container_name
      - labels:
          stream:
          container_name:
      - output:
          source: output
