global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['172.17.0.1:9090']

  - job_name: 'node-app'
    static_configs:
      - targets: ['172.17.0.1:4000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['172.17.0.1:8090']
    scrape_interval: 30s

  - job_name: 'loki'
    static_configs:
      - targets: ['172.17.0.1:3100']
    scrape_interval: 30s

  - job_name: 'postgres'
    static_configs:
      - targets: ['172.17.0.1:9187']
    scrape_interval: 30s
