apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://172.17.0.1:9090
    isDefault: true
    editable: true

  - name: Loki
    type: loki
    access: proxy
    url: http://172.17.0.1:3100
    isDefault: false
    editable: true

  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://172.17.0.1:16686
    isDefault: false
    editable: true
